using System.Collections.Generic;

namespace Esquire.Models
{
    /// <summary>
    /// The coded data associated with a annotation
    /// </summary>
    public class Annotation
    {
        /// <summary>
        /// docId - generated by Document Management
        /// </summary>
        public string docId { get; set; }
        public string DocName { get; set; }
        public int Length { get; set; }
        public int StartPage { get; set; }
        public int EndPage { get; set; }
        public List<AnnotationRect> Rects { get; set; } = new List<AnnotationRect>();
        public string Text { get; set; }
    }
}